// ProjectEuler.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <iostream>

size_t SumOfAllNumbersBelow1000();
size_t SumOfEvenTermsInFibonacciSequenceLessThan4Million();

int main()
{
	std::cout << "*** Results ***\n";
	std::cout << "Problem 1: " << SumOfAllNumbersBelow1000() << std::endl;
	std::cout << "Problem 2: " << SumOfEvenTermsInFibonacciSequenceLessThan4Million() << std::endl;
    return 0;
}

// Problem 1
// Find the sum of all the multiples of 3 or 5 below 1000.

size_t SumOfAllNumbersBelow1000()
{
	size_t sum = 0;

	for (size_t multiple = 0; multiple < 1000; multiple++)
	{
		if ((multiple % 3 == 0) || (multiple % 5 == 0))
		{
			sum += multiple;
		}
	}
	return sum;
}

// Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even - valued terms.

size_t SumOfEvenTermsInFibonacciSequenceLessThan4Million()
{
	size_t x_prev = 1, x = 2, x_next = x; 
	size_t upper_limit = 4000000;

	size_t sum = 0;
	
	while (x_next < upper_limit)
	{
		// Calculate sum of even-valued Fibonacci Sequence
		if ((x % 2) == 0)
		{
			sum += x;
		}

		// Calculate terms of Fiibonacci Sequence
		x_next = x + x_prev;
		x_prev = x;
		x = x_next;
	}
	return sum;
}

// Problem 3